export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_SUCCEED: "AUTHENTICATION_REQUEST_SUCCEED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED",
  UNAUTHENTICATED_REQUEST_INITIATED: "UNAUTHENTICATED_REQUEST_INITIATED",
  UNAUTHENTICATED_REQUEST_SUCCEED: "UNAUTHENTICATED_REQUEST_SUCCEED"
};
