export const sessionActionTypes = {
  AUTHENTICATION_REQUEST_INITIATED: "AUTHENTICATION_REQUEST_INITIATED",
  AUTHENTICATION_REQUEST_SUCCEED: "AUTHENTICATION_REQUEST_SUCCEED",
  AUTHENTICATION_REQUEST_FAILED: "AUTHENTICATION_REQUEST_FAILED",
  UNAUTHENTICATED_REQUEST_INITIATED: "UNAUTHENTICATED_REQUEST_INITIATED",
  UNAUTHENTICATED_REQUEST_SUCCEED: "UNAUTHENTICATED_REQUEST_SUCCEED"
};

export const userActionTypes = {
  USER_UPDATE_REQUEST_INITIATED: "USER_UPDATE_REQUEST_INITIATED",
  USER_UPDATE_REQUEST_SUCCEED: "USER_UPDATE_REQUEST_SUCCEED",
  USER_ADD_SKILL_REQUEST_INITIATED: "USER_ADD_SKILL_REQUEST_INITIATED",
  USER_ADD_SKILL_REQUEST_SUCCEED: "USER_ADD_SKILL_REQUEST_SUCCEED",
  USER_GET_PROFILE_REQUEST_INITIATED: "USER_GET_PROFILE_REQUEST_INITIATED",
  USER_GET_PROFILE_REQUEST_SUCCEED: "USER_GET_PROFILE_REQUEST_SUCCEED"
};

export const skillActionTypes = {
  SKILL_QUERY_REQUEST_INITIATED: "SKILL_QUERY_REQUEST_INITIATED",
  SKILL_QUERY_REQUEST_SUCCEED: "SKILL_QUERY_REQUEST_SUCCEED"
};
